name: Build and Test

on:
  pull_request:
    paths:
      - .github/workflows/build-api-client.yml
      - api-client/**
      - console/**
      - package.json
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.19.0
          run_install: false

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
          node-version: 22

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm -r run lint

      - name: Test
        run: pnpm -r --if-present run test

      - name: Build
        run: pnpm -r run build
